version: "2"

services:
  #
  # Backwork
  #
  backwork:
    build:
      context: ./backwork
    image: bigdatauniversity/backwork:1.6.3
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER
      - MYSQL_PASSWORD

      - PGHOST
      - PGPORT
      - PGDATABASE
      - PGUSER
      - PGPASSWORD

      - MONGO_BACKUP_USER
      - MONGO_BACKUP_PASSWORD
      - MONGO_HOST=mongo
      - SENTRY_DSN
      - SOFTLAYER_USER
      - SOFTLAYER_API_KEY
      - SOFTLAYER_DATACENTER
      - SOFTLAYER_NETWORK=public  # private requires Softlayer VPN
      - SOFTLAYER_CONTAINER
      - SOFTLAYER_PATH

      # IBM Cloud Object Storage config
      - IBM_COS_ACCESS_KEY
      - IBM_COS_SECRET_KEY
      - IBM_COS_INSTANCE_ID
      - IBM_COS_ENDPOINT_URL
      - IBM_COS_BUCKET
      - IBM_COS_PATH

      - LOCAL_BACKUP_NUMBER
      - BACKUP_LOCAL_PATHS
      - MINIMUM_FREE_SPACE

      # config for HTTP request notifier
      - HTTP_NOTIFIER_URL
      - HTTP_NOTIFIER_METHOD
      - HTTP_NOTIFIER_ADD_HEADERS
      - HTTP_NOTIFIER_BEARER_TOKEN
      - HTTP_NOTIFIER_BASIC_AUTH_USER
      - HTTP_NOTIFIER_BASIC_AUTH_PASS
      - HTTP_NOTIFIER_PARAMS
      - HTTP_NOTIFIER_DATA
      - HTTP_NOTIFIER_KEY

    links:
      - mysql
      - mongo

  ##
  # MySQL
  ##
  mysql:
    image: mysql:5.7.20
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  ##
  # Mongo
  # TODO: replace with a public image
  ##
  mongo:
    image: ${REGISTRY_HOST}portal.mongo:0.2.0-e.2
    environment:
      - "MONGO_ADMIN_USER=$MONGO_BACKUP_USER"
      - "MONGO_ADMIN_PASSWORD"
      - "FORUM_MONGO_USER=cs_comments_service"
      - "FORUM_MONGO_PASSWORD"
      - "FORUM_MONGO_DATABASE=cs_comments_service"
      - "EDXAPP_MONGO_USER=edxapp"
      - "EDXAPP_MONGO_PASSWORD"
      - "EDXAPP_MONGO_DB_NAME=edxapp"
